#!/usr/bin/env python3
"""check_report.py -- structural guard for main.tex, run after every edit.

Catches the failure mode that has now bitten twice: a regex that deletes or
extracts a span of LaTeX by scanning to the next sectioning command, without
respecting float environments nested inside it. When a figure sits inside a
deleted subsection, the figure goes too -- and the usual "0 undefined
references" check does NOT catch it, because the sentences citing that figure
were inside the deleted block as well. The deletion is silently self-consistent.

So: compare the label set against a git revision, not just internal consistency.

    python3 check_report.py            # compare against HEAD in the publish repo
    python3 check_report.py <gitrev>   # compare against another revision

Exit status is non-zero if anything regressed.
"""
import re
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
TEX = HERE / "main.tex"
LOG = HERE / "main.log"
PUBLISH = Path.home() / "techreport_publish"

FLOATS = ("figure", "table")


def envs(src, name):
    """Count balanced float environments, tolerating the starred forms."""
    b = len(re.findall(r"\\begin\{%s\*?\}" % name, src))
    e = len(re.findall(r"\\end\{%s\*?\}" % name, src))
    return b, e


def labels(src):
    return set(re.findall(r"\\label\{((?:fig|tab|sec|eq):[^}]+)\}", src))


def crefs(src):
    out = set()
    for m in re.finditer(r"\\(?:c|C)ref\{([^}]+)\}", src):
        out |= {t.strip() for t in m.group(1).split(",")}
    return out


def baseline(rev):
    """The previous version of main.tex, from whichever repo tracks it."""
    for repo in (PUBLISH, HERE.parent):
        try:
            r = subprocess.run(["git", "-C", str(repo), "show", f"{rev}:main.tex"],
                               capture_output=True, text=True, check=True)
            return r.stdout, repo
        except subprocess.CalledProcessError:
            continue
    return None, None


def expand_inputs(src, root=HERE, depth=0):
    r"""Inline every \input{...} so labels defined in a generated table file are visible.

    The Results tables are generated by analysis/emit_tex.py into their own .tex files and
    pulled in with \input. Without this, every \cref to a generated table looks like a
    dangling reference to this guard while LaTeX itself resolves it fine -- i.e. the guard
    would cry wolf on three real, working tables and train me to ignore it.
    """
    if depth > 4:
        return src

    def sub(m):
        p = (root / m.group(1)).with_suffix(".tex")
        return expand_inputs(p.read_text(), root, depth + 1) if p.exists() else m.group(0)

    return re.sub(r"\\input\{([^}]+)\}", sub, src)


def main():
    rev = sys.argv[1] if len(sys.argv) > 1 else "HEAD"
    src = TEX.read_text()
    # Float counts and balance are checked on main.tex alone (that is where an unbalanced
    # environment would be introduced); labels and crefs are resolved across \input files.
    full = expand_inputs(src)
    fails, warns = [], []

    # 1. EVERY environment is balanced, not just the floats. A regex that cuts a
    #    span "up to the next blank line" will happily take an \end{...} with it,
    #    which silently boxes the rest of the document.
    begins = re.findall(r"\\begin\{([A-Za-z*]+)\}", src)
    ends = re.findall(r"\\end\{([A-Za-z*]+)\}", src)
    for name in sorted(set(begins) | set(ends)):
        b, e = begins.count(name), ends.count(name)
        if b != e:
            fails.append(f"unbalanced environment '{name}': {b} begin vs {e} end")

    # 2. nothing lost against the baseline -- the check that would have caught it
    old, repo = baseline(rev)
    if old is None:
        warns.append(f"no baseline for '{rev}'; skipped the regression check")
    else:
        for f in FLOATS:
            # Count on the EXPANDED source. Moving a hand-written table into a generated
            # \input file drops the count in main.tex while the table still renders, which
            # reported a regression on an improvement.
            nb, _ = envs(full, f)
            ob, _ = envs(expand_inputs(old), f)
            if nb < ob:
                fails.append(f"{f} count fell {ob} -> {nb} vs {rev} ({repo.name})")
        gone = labels(old) - labels(full)
        if gone:
            fails.append(f"labels removed vs {rev}: {', '.join(sorted(gone))}")

    # 3. no float is orphaned -- defined but never referred to
    for lab in sorted(labels(full)):
        if lab.startswith(("fig:", "tab:")) and lab not in crefs(full):
            fails.append(f"{lab} is never \\cref'd (a figure nobody points at)")

    # 4. every reference resolves
    for t in sorted(crefs(full) - labels(full)):
        fails.append(f"\\cref{{{t}}} has no matching \\label")

    # 5. the compiler agrees
    if LOG.exists():
        log = LOG.read_text(errors="ignore")
        n = len(re.findall(r"undefined (?:reference|citation)", log, re.I))
        if n:
            fails.append(f"{n} undefined reference/citation in main.log")
    else:
        warns.append("main.log absent; compile before trusting this")

    nf, _ = envs(full, "figure")
    nt, _ = envs(full, "table")
    print(f"main.tex: {nf} figures, {nt} tables, {len(labels(full))} labels "
          f"(with \\input files expanded)")
    for w in warns:
        print(f"  warn  {w}")
    for f in fails:
        print(f"  FAIL  {f}")
    print("OK" if not fails else f"{len(fails)} problem(s)")
    return 1 if fails else 0


if __name__ == "__main__":
    sys.exit(main())
